<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.3 (Python 3.8.5 on win32)" generated="20210621 12:43:16.578" rpa="false" schemaversion="2">
<suite id="s1" name="Data Driven 03" source="C:\Users\gazi\PycharmProjects\robotProject\Tests\Data_Driven_03.robot">
<kw name="start_test" library="common" type="SETUP">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>${url}</arg>
<arg>${browser}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20210621 12:43:16.961" level="INFO">Opening browser 'chrome' to base url 'https://www.saucedemo.com/'.</msg>
<status status="PASS" starttime="20210621 12:43:16.960" endtime="20210621 12:43:21.440"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" starttime="20210621 12:43:21.441" endtime="20210621 12:43:21.567"/>
</kw>
<kw name="Sleep" library="BuiltIn">
<arg>2</arg>
<doc>Pauses the test executed for the given time.</doc>
<msg timestamp="20210621 12:43:23.570" level="INFO">Slept 2 seconds</msg>
<status status="PASS" starttime="20210621 12:43:21.567" endtime="20210621 12:43:23.570"/>
</kw>
<status status="PASS" starttime="20210621 12:43:16.960" endtime="20210621 12:43:23.570"/>
</kw>
<test id="s1-t1" name="Verify login">
<kw name="invalid login scenarios" library="common">
<arg>${username}</arg>
<arg>${password}</arg>
<arg>${error_msg}</arg>
<msg timestamp="20210621 12:43:23.575" level="FAIL">Variable '${username}' not found.</msg>
<status status="FAIL" starttime="20210621 12:43:23.572" endtime="20210621 12:43:23.575"/>
</kw>
<status status="FAIL" starttime="20210621 12:43:23.570" endtime="20210621 12:43:23.575">Variable '${username}' not found.</status>
</test>
<kw name="stop_test" library="common" type="TEARDOWN">
<kw name="Close Browser" library="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="PASS" starttime="20210621 12:43:23.578" endtime="20210621 12:43:25.965"/>
</kw>
<status status="PASS" starttime="20210621 12:43:23.578" endtime="20210621 12:43:25.966"/>
</kw>
<status status="FAIL" starttime="20210621 12:43:16.581" endtime="20210621 12:43:25.966"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Data Driven 03">Data Driven 03</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210621 12:43:16.569" level="ERROR">Error in file 'C:\Users\gazi\PycharmProjects\robotProject\Tests\Data_Driven_03.robot' on line 18: Setting 'Suite Setup' is allowed only once. Only the first value is used.</msg>
<msg timestamp="20210621 12:43:16.570" level="ERROR">Error in file 'C:\Users\gazi\PycharmProjects\robotProject\Tests\Data_Driven_03.robot' on line 19: Setting 'Suite Teardown' is allowed only once. Only the first value is used.</msg>
<msg timestamp="20210621 12:43:16.570" level="ERROR">Error in file 'C:\Users\gazi\PycharmProjects\robotProject\Tests\Data_Driven_03.robot' on line 20: Setting 'Test Template' is allowed only once. Only the first value is used.</msg>
<msg timestamp="20210621 12:43:16.926" level="ERROR">Error in file 'C:\Users\gazi\PycharmProjects\robotProject\Tests\Data_Driven_03.robot' on line 6: Resource file '..\resources\Data_Driven_01_resource.robot' does not exist.</msg>
<msg timestamp="20210621 12:43:16.959" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: AttributeError: No "Test Template" keyword found for first test case.</msg>
</errors>
</robot>
